### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by sander1**
Hi! I made some small changes to the fork in plexinc-plugins. This version has just been added to the Channel Directory.

Thank you for contributing!

PS: You can send pul requests on Github if you make any changes or updates in the future.

### CODE REVIEW

**Comment by zakalibit** [comment]
Thanks, a lot, this is my first plugin for plex :)
I have merged your changes.

I'd like to update plex plugin with live streams and I'm wandering what is
the situation with aes encrypted hls streams? rte has encrypted live
streams, that kodi for example can not play, even after encrypting them
kodi wont play  h264 encoded stream, for kodi plugin I had to write a
pythons service that decrypts the stream then filters it trough ffmpeg.

Thanks,
Alex

**Comment by zakalibit** [comment]
I noticed another issue, after changing icon from png to jpg, it does not
show it as default icon in the channels list.
Should I revert it back to png?

Alex

**Comment by sander1** [comment]
> I noticed another issue, after changing icon from png to jpg, it does not
> show it as default icon in the channels list.
> Should I revert it back to png?

Hi! This issue should be fixed with https://github.com/zakalibit/RTEPlayer.bundle/pull/2. The `R()` is not used in the `@handler`.

**Comment by sander1** [comment]
> I'd like to update plex plugin with live streams and I'm wandering what is
> the situation with aes encrypted hls streams? rte has encrypted live
> streams, that kodi for example can not play, even after encrypting them
> kodi wont play  h264 encoded stream, for kodi plugin I had to write a
> pythons service that decrypts the stream then filters it trough ffmpeg.

Only some Plex clients can handle AES encrypted HTTP Live Streams at the moment (iOS, Android and Roku). There has been talk about letting PMS transcode those kind of streams so other Plex clients can play them too, but this has not yet been implemented.

**Comment by zakalibit** [comment]
It is quite easy to the decrypt AES encrypted hls, does PMS have any python
customization points, as it is easy to do in python.
It looks like plex is using ffmpeg, as there is code in ffmpeg that is
aimed to do it, but it looks broken, I tried to get my head around it, but
I need more time for this.

Alex

**Comment by zakalibit** [comment]
Can not see it in the Channel Directory, was it removed for some reason?

Alex

**Comment by sander1** [comment]
> Can not see it in the Channel Directory, was it removed for some reason?

We've received a formal complaint from RTE and they demanded we take down the channel :'(

**Comment by zakalibit** [comment]
I see, thanks you any way for the fixes.

Regards,
Alex

**Pull request merged**
